<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $this \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

$ascUrlParams = ['product_list_order' => $block->getCurrentOrder(), 'product_list_dir' => 'asc'];
$descUrlParams = ['product_list_order' => $block->getCurrentOrder(), 'product_list_dir' => 'desc'];
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($this->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $this->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="<?php echo $block->getUrl('*/*', ['_current' => true, '_use_rewrite' => true, '_query' => $ascUrlParams]) ?>"
           class="action sorter-action sort-desc"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="<?php echo $block->getUrl('*/*', ['_current' => true, '_use_rewrite' => true, '_query' => $descUrlParams]) ?>"
           class="action sorter-action sort-asc"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
