<?php
/**
 * Featured Products Slider
 */
?>
<?php
// $catId = $block->getParentCategory();
// $subcategory = $block->getCategory($catId);
// $subcats = $subcategory->getChildrenCategories();
$catId = $block->getData("category_id");
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subcats = $subCategory->getChildrenCategories();

$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php
//$_productCollection = $this->getLoadedProductCollection();
?>
<?php //if ($_productCollection && ($_collectionSize = $this->getCollectionCount())): ?>
<?php if ($subcats): ?>
    <?php
    //$_helper = $this->getCatalogHelperOutput();
    $theme = $this->getDataHelper();
    $helpLabels = $this->getLabelHelper();
    $helperImg = $this->getImageHelper();
    $helperAddToLinks = $this->helper('Infortis\Base\Helper\AddToLinks');

    $showCart = ($this->getHideButton()) ? false : true;
    $imageTypeId = 'category_page_grid';
    $showAltImage = $theme->getCfg('category/alt_image');

    $sliderClasses = '';
    $gridClasses = '';
    $hash = $this->getFrontendHash();
    $sliderId = "itemslider-featured-{$hash}";

    //
    // Slider configuration
    // ----------------------------------------------

    // Single item
//    if ($_collectionSize == 1)
//    {
//        $sliderClasses .= ' single-item';
//    }

    // Breakpoints
    $breakpoints = $this->getBreakpoints();
    if ($breakpoints === NULL)
    {
        $breakpoints = '[0, 1], [320, 1], [480, 3], [768, 3], [992, 3], [1200, 3]';
    }

    // Responsive mode on/off and number of items
    $isResponsive = $this->getIsResponsive();
    if ($isResponsive === NULL)
    {
        $isResponsive = true;
    }

    if (!$isResponsive)
    {
        $showItems = $this->getShowItems();
        if (!$showItems)
        {
            $showItems = 5;
        }
    }

    // Timeout (automatic scrolling)
    $timeout = $this->getTimeout();
    if ($timeout === NULL)
    {
        $timeout = intval($theme->getCfg('product_slider/timeout'));
    }
    else
    {
        $timeout = intval($timeout);
    }

    // Number of items that should move on scroll
    $move = $this->getMove();
    if ($move === NULL)
    {
        $move = 0;
    }
    else
    {
        $move = intval($move);
    }

    // Loop
    $loop = $this->getLoop();
    if ($loop === NULL)
    {
        $loop = $theme->getCfg('product_slider/loop');
    }

    // Speed (arrows / touch swipe)
    $speed = intval($theme->getCfg('product_slider/speed'));

    // Speed (automatic scrolling / pagination)
    $autoSpeed = intval($theme->getCfg('product_slider/auto_speed'));

    // Pause on mouse hover
    $pause = $theme->getCfg('product_slider/pause');

    // Lazy loading
    $lazy = $theme->getCfg('product_slider/lazy');

    // Pagination
    $pagination = $this->getPagination();

    //
    // Grid configuration
    // ----------------------------------------------

    // Product image dimensions
    $keepAspectRatio = $this->getData('keep_aspect_ratio');
    if ($keepAspectRatio === NULL)
    {
        $keepAspectRatio = $theme->getCfg('product_slider/keep_aspect_ratio');
    }

    // Image width
    $imgWidth = $this->getData('img_width');
    if ($imgWidth === NULL)
    {
        // Default width has to be defined in the template to allow "Keep aspect ratio" option
        $imgWidth = 170;
    }
    else
    {
        $imgWidth = intval($imgWidth);
    }

    // If keep aspect ratio, delete height
    if ($keepAspectRatio)
    {
        $imgHeight = null;
    }
    else
    {
        $imgHeight = $imgWidth;
    }

    // If height parameter exists, it overrides current value of height
    if ($this->getData('img_height') !== NULL)
    {
        $imgHeight = intval($this->getData('img_height'));
    }

    // Size of item's elements
    $size = $this->getSize();
    if ($size)
    {
        $gridClasses = ' ' . $size;
    }
    else
    {
        if (isset($showItems))
        {
            if ($showItems >= 8)
            {
                $gridClasses = ' size-xs';
            }
            elseif ($showItems >= 6)
            {
                $gridClasses = ' size-s';
            }
        }
    }

    // Align elements to the center
    if ($this->getCentered())
    {
        $gridClasses .= ' centered';
    }

    // Equal height of items
    if ($this->getData('equal_height'))
    {
        $gridClasses .= ' equal-height';
    }

    ?>
    <div class="block itemslider<?php if($sliderClasses) echo $sliderClasses; ?> slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
        <h1 class="section-title border-bottom"><?php echo $this->getBlockName(); ?></h1>
        <div class="block-content">
            <div class="products-grid<?php if($gridClasses) echo $gridClasses; ?>">
                <div id="<?php echo $sliderId; ?>" class="products list items product-items">
                    <?php //foreach ($_productCollection as $_product): ?>
                    <?php foreach ($subcats as $subcat): ?>
                        <?php  //$_category = $block->getCategory($subcat->getId());
                        $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
                        if(!isset($_category)){ continue;}
                        $_imgHtml = '';
                        if ($_imgUrl = $_category->getImageUrl()) {
                            if ($lazy){
                                $_imgHtml = '<img class="lazyOwl" data-src="' . $_imgUrl . '" />';
                            }
                            else{
                                $_imgHtml = '<img src="' . $_imgUrl . '" />';
                            }

                            $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
                        }

                        ?>
                        <div class="item">
                            <div class="product-item-info category-item">
                                <div class="product-item-img" <?php /*style="max-width:<?php echo $imgWidth; ?>px;" */?> >

                                    <a href="<?php /* @escapeNotVerified */ echo $_category->getUrl() ?>" title="" class="seemore product-image">
                                        <h3 class="name"><?php echo $_category->getName(); ?></h3>
                                        <div class="image">
                                            <?php echo $_imgHtml?>
                                        </div>
                                        <?php echo __('See More')?>
                                    </a>

                                </div> <!-- end: product-item-img -->
                            </div> <!-- end: product-item-info -->
                        </div>
                    <?php endforeach; ?>
                </div> <!-- end: element with the itemslider ID -->
            </div> <!-- end: products-grid -->
        </div> <!-- end: block-content -->
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
        }
    }
    </script>
    <?php endif; ?>
    <script type="text/javascript">
        //<![CDATA[

        requirejs(['jquery','owlcarousel'], function(jQuery, owl)
        {
            jQuery(function($) {
                var owl = $('#<?php echo $sliderId; ?>');
                owl.owlCarousel({

                    <?php if ($lazy): ?>
                    lazyLoad: true,
                    <?php endif; ?>
                    <?php if(!$isResponsive): ?>
                    responsive: false,
                    items: <?php echo $showItems; ?>,
                    <?php else: ?>
                    itemsCustom: [ <?php echo $breakpoints; ?> ],
                    responsiveRefreshRate: 50,
                    <?php endif; ?>
                    <?php if ($speed): ?>
                    slideSpeed: <?php echo $speed; ?>,
                    <?php endif; ?>
                    <?php if ($autoSpeed): ?>
                    paginationSpeed: <?php echo $autoSpeed; ?>,
                    <?php endif; ?>
                    <?php if ($move !== 1): ?>
                    scrollPerPage: true,
                    <?php endif; ?>
                    <?php if ($timeout): ?>
                    autoPlay: <?php echo $timeout; ?>,
                    <?php endif; ?>
                    <?php if ($pause): ?>
                    stopOnHover: true,
                    <?php endif; ?>
                    <?php if ($loop): ?>
                    rewindNav: true,
                    rewindSpeed: 600,
                    <?php else: ?>
                    rewindNav: false,
                    <?php endif; ?>
                    <?php if ($pagination): ?>
                    pagination: true,
                    <?php else: ?>
                    pagination: false,
                    <?php endif; ?>
                    navigation: true,
                    navigationText: false

                });
            });
        });

        //]]>
    </script>
<?php endif; ?>
