<?php
/**
 * FAQs And Product Questions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FAQs And Product Questions
 * @author     Asif Hussain <support@fmeextensions.com>
 *
 * @copyright  Copyright 2012 www.fmeextensions.com All right reserved
 */
/** @var $block \CustomConcepts\Prodfaqs\Block\Faq\Topics */
?>
<?php
$prodfaqsHelper = $block->getProdfaqsHelper();
$maxDisplay = $prodfaqsHelper->getFaqMaxTopic();
$collection = $block->getSideTopics($maxDisplay);
$counter = 0;
?>

<?php if ($prodfaqsHelper->getFaqBlock()): ?>

    <div class="block block-faqs" style="margin-top: 0;">
        <h1 class="section-title special"><?php echo __('Choose another Topic'); ?></h1>

        <?php if (count($collection) == 0) : ?>
            <div class="block-content">
                <p class="empty"><?php echo __('No Faqs find yet!') ?></p>
            </div>
        <?php else : ?>
            <div class="sidetopics" data-mage-init='{"current_side_topic": {}}'>
                <ul>
                    <?php foreach ($collection as $_topic): ?>
                        <li <?php if($_topic['current']): ?> class="current" <?php endif; ?>><a href="<?php echo $block->getFaqUrl() . $_topic['identifier']; ?>"><?php echo $_topic['title']; ?></a></li>
                    <?php endforeach; ?>

                    <li><a href="<?php echo $block->getFaqUrl(); ?>"><?php echo __('View all topics') ?></a></li>
                </ul>
            </div>

        <?php endif; ?>

    </div>

<?php endif; ?>

