<?php
/**
 * FAQs And Product Questions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FAQs And Product Questions
 * @author     Asif Hussain <support@fmeextensions.com>
 *
 * @copyright  Copyright 2012 www.fmeextensions.com All right reserved
 */
?>
<?php
$prodfaqsHelper = $block->getProdfaqsHelper();
$maxDisplay = $prodfaqsHelper->getFaqMaxTopic();
$collection = $block->getMainTopics($maxDisplay);
?>

<?php if ($prodfaqsHelper->getFaqBlock()): ?>

    <div class="block block-faqs">
        <div class="section-topic-title">
            <strong><?php echo __('Topics'); ?></strong>
        </div>

        <?php if (count($collection) == 0) : ?>
            <div class="block-content">
                <p class="empty"><?php echo __('No Faqs find yet!') ?></p>
            </div>
        <?php else : ?>
            <div class="topicwrap">
                <?php foreach ($collection as $_topic): ?>
                    <?php if($prodfaqsHelper->getFaqBlockViewBy() == 'image'): ?>
                        <div class="topicImageholder">
                            <?php if ($_topic->getTopicOrder() == 1): ?>
                                <a href="<?php echo '#faqcontainer'; ?>">
                            <?php else : ?>
                                <a href="<?php echo $block->getUrl( $block->getFaqUrl() . $_topic->getIdentifier()); ?>">
                            <?php endif; ?>
                                    <?php $image = $_topic->getImage(); ?>
                                    <?php if($image): ?>
                                        <img src="<?php echo $image; ?>" alt="">
                                    <?php else: ?>
                                        <h2 class="topictitle"> <?php echo $_topic->getTitle(); ?></h2>
                                    <?php endif; ?>
                                </a>
                                <br>
                                <strong> <?php echo $_topic->getTitle(); ?></strong>
                        </div>
                    <?php else: ?>
                        <div class="topicholder">
                            <?php if ($_topic->getTopicOrder() == 1): ?>
                            <a href="<?php echo '#faqcontainer'; ?>">
                                <?php else : ?>
                                <a href="<?php echo $block->getUrl( $block->getFaqUrl() . $_topic->getIdentifier()); ?>">
                                    <?php endif; ?>
                                    <h2 class="topictitle"> <?php echo $_topic->getTitle(); ?></h2>
                                    <p class="topictext"><?php echo $_topic->getSubtitle(); ?></p>
                                </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>

            </div>

        <?php endif; ?>

    </div>

<?php endif; ?>

