<div class="team-grid-template">
    <div class="team-list">
        <ul>
            <li class="team-member">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/michiel-van-de-plassche_1.jpg'); ?>" alt="Michiel van de Plassche">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Michiel van de Plassche'); ?></p>
                    <div class="position"><?php echo __('CEO &amp; Founder '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/marc-hilhorst.jpg'); ?>" alt="Marc Hilhorst">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Marc Hilhorst'); ?></p>
                    <div class="position"><?php echo __('Managing Partner '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/elise-schoon.jpg'); ?>" alt="Elise Schoon">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Elise Schoon'); ?></p>
                    <div class="position"><?php echo __('Managing Partner '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member">
                <div class="user-img">
                    <img class="member_avatar " src="<?php echo $block->getViewFileUrl('images/team/jeroen-van-rijn.jpg'); ?>" alt="Jeroen van Rijn">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Jeroen van Rijn'); ?></p>
                    <div class="position"><?php echo __('CTO '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/levi-meyer.jpg'); ?>" alt="Levi Meyer">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Levi Meyer'); ?></p>
                    <div class="position"><?php echo __('Marketing Manager '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/dave-crombeen.jpg'); ?>" alt="Dave Crombeen">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Dave Crombeen'); ?></p>
                    <div class="position"><?php echo __('Print Operator '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/michelle-caldeira-fernandez.jpg'); ?>" alt="Michelle Caldeira FDez">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Michelle Caldeira FDez'); ?></p>
                    <div class="position"><?php echo __('Marketing Manager '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar " src="<?php echo $block->getViewFileUrl('images/team/sandy-ter-meulen.jpg'); ?>" alt="Sandy Termeulen">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Sandy Termeulen'); ?></p>
                    <div class="position"><?php echo __('Production Manager '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/toby-van-der-ven.jpg'); ?>" alt="Toby Van Der Ven">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Toby Van Der Ven'); ?></p>
                    <div class="position"><?php echo __('Product Manager '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/jarmilla.jpg'); ?>" alt="Jarmila Smolova">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Jarmila Smolova'); ?></p>
                    <div class="position"><?php echo __('Production Shift Lead '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/nick-site.jpg'); ?>" alt="Nick Rengers">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Nick Rengers'); ?></p>
                    <div class="position"><?php echo __('Head of Operations '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/Maria-cutted.jpg'); ?>" alt="Maria Garrido">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Maria Garrido'); ?></p>
                    <div class="position"><?php echo __('Support Coordinator '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/Theodor-cutted.jpg'); ?>" alt="Theodor Felix Iacob">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Theodor Felix Iacob'); ?></p>
                    <div class="position"><?php echo __('Fullstack Developer '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
            <li class="team-member slide-up" style="display: none;">
                <div class="user-img">
                    <img class="member_avatar" src="<?php echo $block->getViewFileUrl('images/team/khalil-cutted.png'); ?>" alt="Khalil Chourou">
                </div>
                <div class="content">
                    <p class="name"><?php echo __('Khalil Chourou'); ?></p>
                    <div class="position"><?php echo __('Data Engineer - Analyst '); ?></div>
                    <div class="team-social">
                    </div>
                </div>
            </li>
        </ul>
    </div>

    <div class="clearfix"></div>

    <div class="center-text margin-tb-30">
        <strong class="text-uppercase"><?php echo __('See The Whole Team'); ?></strong>
        <p><a class="button view-team"><i class="ic ic-down"></i></a></p>
    </div>
</div>

<script type="text/javascript">
    requirejs(['jquery'], function(jQuery) {
        jQuery(".view-team").click(function () {
            jQuery(this).toggleClass('open');

            jQuery('.slide-up').slideToggle('slow');
        });

        // Optimalisation: Store the references outside the event handler:
        var $window = jQuery(window);

        function checkWidth() {
            var windowsize = $window.width();
            jQuery('.slide-up').removeClass('slide-up').show();
            jQuery(".team-member").each(function (index) {
                if (windowsize < 768 && index > 2) {
                    jQuery(this).addClass('slide-up').hide();

                } else {

                    if (index > 4) {
                        jQuery(this).addClass('slide-up').hide();
                    }
                }
            });

        }
        checkWidth();
        jQuery(window).resize(checkWidth);
    });
</script>


