<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="remove-item-btn"
   data-role="remove-item"
   data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson() ?>'>x</a>

