<?php
namespace CustomConcepts\RelatedProducts\Block\Adminhtml;


use Magento\Framework\View\Element\Template;

class RelatedProducts extends \Magento\Framework\View\Element\Template
{
    protected $productRepository;

    public function __construct(
        Template\Context $context,
        \Magento\Catalog\Api\ProductRepositoryInterface $productRepository,
        array $data = []
    ){
        $this->productRepository = $productRepository;
        parent::__construct($context, $data);
    }

    public function _prepareLayout()
    {
        $params = $this->getRequest()->getParams();
        $this->setData('params', $params);
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getSelectedParams(){
        $params = $this->getData('params');
        return $params['selected'];
    }

    public function getAssignUrl(){
        return $this->getUrl('*/*/assign');
    }

    public function getRemoveUrl(){
        return $this->getUrl('*/*/remove');
    }

    public function getProduct($productId){
        return $this->productRepository->getById($productId);
    }
}
