<?php
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="welcome-msg">
    <p class="hello"><strong><?= __('Hello, %1!', $block->escapeHtml($block->getName())) ?></strong></p>
    <p><?= __('From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.') ?></p>
</div>
