<?php
/**
 * @var \Infortis\Base\Block\Catalog\Product\View $block
 */
?>
<?php
$theme = $block->getHelperTheme();
$helperProductView = $block->getHelperProductView();
$helperLabels = $this->helper('Infortis\Base\Helper\Labels');
$helperAddToLinks = $this->helper('Infortis\Base\Helper\AddToLinks');
$ratingSummary = $this->getRatingSummary();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$_product = $block->getProduct();

//Get grid classes for product page sections
$grid = $helperProductView->getGridClasses();

//Get positions of blocks
$position = $helperProductView->getPositions();

//Brand info
$brandHtml = $block->getChildHtml('brand-info');
if (!empty($brandHtml)) {
    if (isset($p[$position['brand']])) {
        $p[$position['brand']] = $p[$position['brand']] . $brandHtml;
    } else {
        $p[$position['brand']] = $brandHtml;
    }
}

//Product collateral data
$collateralHtml = $block->getChildHtml('product.info.details');
if (!empty($collateralHtml)) {
    if (isset($p[$position['collateral']])) {
        $p[$position['collateral']] = $p[$position['collateral']] . $collateralHtml;
    } else {
        $p[$position['collateral']] = $collateralHtml;
    }
}

//Related products
$relatedProductsHtml = $block->getChildHtml('catalog.product.related');
if (!empty($relatedProductsHtml)) {
    if (isset($p[$position['related']])) {
        $p[$position['related']] = $p[$position['related']] . $relatedProductsHtml;
    } else {
        $p[$position['related']] = $relatedProductsHtml;
    }
}

//Up-sell products
$upsellProductsHtml = $block->getChildHtml('product.info.upsell');
if (!empty($upsellProductsHtml)) {
    if (isset($p[$position['upsell']])) {
        $p[$position['upsell']] = $p[$position['upsell']] . $upsellProductsHtml;
    } else {
        $p[$position['upsell']] = $upsellProductsHtml;
    }
}

/** SET rating summary data */
$block->setRatingSummaryData();
$ratingSummary = $block->getRatingSummary();
$reviewsCount = $block->getReviewsCount();

/** GET special price */
/** @var CustomConcepts\Base\Helper\Price $priceHelper */
$priceHelper = $this->helper('CustomConcepts\Base\Helper\Price');
$price = $block->getProductFormattedPrice();
$origPrice = null;
if($priceHelper->hasSpecialPrice($_product)){
    $price = $priceHelper->getFormattedSpecialPrice($_product);
    $origPrice = $priceHelper->getFormattedOriginalPrice($_product);
}

/** Add to cart URL for simple products */
/** @var Magento\Catalog\Block\Product\ListProduct $productListBlock */
$productListBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
$currentRoute = $block->getRequest()->getRouteName() . '/' . $block->getRequest()->getControllerName() . '/' . $block->getRequest()->getActionName();
$addToCartUrl = '';
if($currentRoute == 'catalog/product/view'){
    $addToCartUrl = $productListBlock->getAddToCartUrl($_product);
} elseif($itemId = $this->getRequest()->getParam('id')) {
    $addToCartUrl = $block->getUrl('checkout/cart/updateItemOptions', ['_current' => true,'_use_rewrite' => true, '_query' => ['id' => $itemId]]);
}
?>

<div class="product-view product-columns-wrapper container product-image zoom-inside">
    <div class="top-container mobile-show">
        <div class="product-name">
            <h1 itemprop="name">
                <?php
               $_subname = '';
               $_nameFull = $_helper->productAttribute($_product, $_product->getName(), 'name');
                if(($pos_dash = strpos($_nameFull, '-'))!==false){
                    $_name = substr($_nameFull, 0, $pos_dash-1);
                    $_subname = substr($_nameFull, $pos_dash+1);
                }else{
                    $_name = $_nameFull;
                }
                echo $_name ?>
                <span class="smallprodname"><?php echo $_subname ?></span>
            </h1>
        </div>

        <div class="rating-box mobile-hide">
            <div class="rating" style="width:0%"></div>
        </div>
        <div class="reviews-actions mobile-show">
            <?php if($ratingSummary && $reviewsCount): ?>
                <div class="rating-summary">
                    <div class="rating-result" id="goto-reviews-form" title="<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                    <span style="width:<?= $block->escapeHtmlAttr($ratingSummary); ?>%">
                        <span>
                            <span itemprop="ratingValue"><?= $block->escapeHtml($ratingSummary); ?></span>% of <span itemprop="bestRating">100</span>
                        </span>
                    </span>
                    </div>
                </div>
            <?php else: ?>
                <a class="action add" href="#review-form">
                    <?= __('Be the first to review this product') ?>
                </a>
            <?php endif; ?>
        </div>
    </div>

    <div class="product-img-column grid12-4">
        <?php echo $block->getChildHtml('product.info.media'); ?>
        <?php //echo $helperLabels->getLabels($block->getProduct()); ?>
        <?php if (isset($p['imgCol_1'])) echo $p['imgCol_1']; ?>

        <?php //Container at the bottom ?>
        <?php echo $block->getChildHtml('container_product_image_1'); ?>

        <div class="non-collapsing-column-placeholder"></div>
    </div>

    <?php //TODO: remove old classes such as "product-shop" (if possible. check it first, test old styles) ?>
    <div class="product-primary-column product-shop grid12-5">
        <div class="product-name mobile-hide">
            <h1 itemprop="name"><?php echo $block->getProductTitle(); ?></h1>
        </div>

        <?php
        if(isset($ratingSummary) && $reviewsCount): ?>
            <div class="rating-box mobile-hide">
                <div class="rating" style="width:<?php echo $ratingSummary ?>%;"></div>
            </div>
            <div class="reviews-actions">
                <a class="action view" id="goto-reviews-form" href="#">
                    <span><?= $reviewsCount ?></span>&nbsp;<span><?= __('Reviews') ?></span>
                </a>
                <a class="action add" href="#"><?= __('Add Your Review') ?></a>
            </div>
        <?php else: ?>
        <div class="rating-box mobile-hide">
            <div class="rating" style="width:0%"></div>
        </div>
        <div class="reviews-actions">
            <a class="action add" href="#review-form">
                <?= __('Be the first to review this product') ?>
            </a>
        </div>
        <?php endif; ?>

        <div class="short-description">
            <div class="std" itemprop="description"><?php echo $block->getChildHtml('product.info.main'); ?></div>
        </div>

        <p class="availability in-stock">
            <?= $block->getLayout()->createBlock('CustomConcepts\Estimations\Block\Product\View\Stock')->toHtml(); ?><br/>
            <span class="price-text" style="color: #bbb"><?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('price_text')->toHtml(); ?></span>
        </p>

        <?php //Container at the top ?>
        <?php echo $block->getChildHtml('container_product_primary_1'); ?>

        <?php if (isset($p['primCol_1'])) echo $p['primCol_1']; ?>

        <div class="stickyfooter">
            <?php if($priceHelper->hasSpecialPrice($_product)): ?>
            <div class="price-box-special">
                <span class="orig-price" id="product-price-<?php echo $this->getProduct()->getId(); ?>">
                    <span class="price"><?= $origPrice; ?></span>
                </span>
                <span class="special-price" id="product-price-<?php echo $this->getProduct()->getId(); ?>">
                    <span><?= __('Special Price') ?></span>&nbsp;<span class="price"><?= $price ?></span>
                </span>
            </div>
            <?php else: ?>
            <div class="price-box">
                <span class="regular-price" id="product-price-<?php echo $this->getProduct()->getId(); ?>">
                    <span class="price"><?= $price ?></span>
                </span>
            </div>
            <?php endif; ?>

            <form data-role="tocart-form" data-product-sku="<?= $_product->getSku(); ?>" action="<?php echo $addToCartUrl; ?>" method="post" id="product_addtocart_form">
                <?php echo $block->getBlockHtml('formkey')?>
                <?= $block->getBlockHtml('product.info.addtocart'); ?>
            </form>
        </div>

        <?php if (isset($p['primCol_2'])) echo $p['primCol_2']; ?>

        <?php //Container at the bottom ?>
        <?php echo $block->getChildHtml('container_product_primary_2'); ?>
    </div>

    <?php if (isset($grid['secCol'])): ?>
        <div class="product-secondary-column custom-sidebar-right <?php echo $grid['secCol']; ?> no-right-gutter">
            <div class="inner">

                <?php //Container at the top ?>
                <?php echo $block->getChildHtml('container_product_secondary_1'); ?>

                <?php if (isset($p['secCol_1'])) echo $p['secCol_1']; ?>
                <?php echo $block->getChildHtml('block_product_secondary_bottom'); ?>
                <?php if (isset($p['secCol_2'])) echo $p['secCol_2']; ?>

                <?php //Container at the bottom ?>
                <?php echo $block->getChildHtml('container_product_secondary_2'); ?>

                <?php //if (isset($p['secCol_3'])) echo $p['secCol_3']; ?>

                <?php //TODO: ?>
                <?php if ($tmpHtml = $block->getChildHtml('product_secondary_top_placeholder')): ?>
                    <div class="feature-wrapper bottom-border"><?php echo $tmpHtml; ?></div>
                <?php endif; ?>

            </div>
        </div>
    <?php endif; ?>

    <div class="product-lower-primary-column grid12-9">

        <?php echo $block->getChildHtml('bundle.options.container'); ?>
        <?php echo $block->getChildHtml('moved.downloadable.product-info'); ?>

        <?php //Container at the top. Important: required AFTER the bundle and downloadable blocks. ?>
        <?php echo $block->getChildHtml('container_product_lower_primary_1'); ?>

        <?php if (isset($p['lowerPrimCol_1'])) echo $p['lowerPrimCol_1']; ?>

        <?php //Container at the bottom ?>
        <?php echo $block->getChildHtml('container_product_lower_primary_2'); ?>

    </div>

    <?php if (isset($grid['lowerSecCol'])): ?>
        <div class="product-lower-secondary-column custom-sidebar-right <?php echo $grid['lowerSecCol']; ?>">
            <div class="inner">

                <?php //Container at the top ?>
                <?php echo $block->getChildHtml('container_product_lower_secondary_1'); ?>

                <?php if (isset($p['lowerSecCol_1'])) echo $p['lowerSecCol_1']; ?>

                <?php //Container at the bottom ?>
                <?php echo $block->getChildHtml('container_product_lower_secondary_2'); ?>

            </div>
        </div>
    <?php endif; ?>
</div>

<script type="text/javascript">
    requirejs(['jquery'], function(jQuery) {
        jQuery(window).on('load resize', function () {
            jQuery('.stickyfooter').removeClass('stickyfooter1024')
            if (window.innerWidth == 768 && window.innerHeight == 1024) {
                jQuery('.stickyfooter').addClass('stickyfooter1024')
            }
        });
        jQuery("#goto-reviews-form, .reviews-actions .add").click(function(e) {
            e.preventDefault();
            jQuery('#tab-label-reviews-title').click();
            jQuery('html, body').animate({
                scrollTop: jQuery("#review-form").offset().top -20
            }, 1000);
        });
    });
</script>
