<?php
/**
* @var CustomConcepts\Gocustomizer\Block\Gocustomizer $block
*/
/** @var \CustomConcepts\GoCustomizer\Block\Gocustomizer $block */
$block->initializeBlock();
?>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <title><?= __('GoCustomized - Design your product')?></title>
    <script type="text/javascript" src="<?php echo  $block->getConfigValue('gocustomizer/general/customizer_url') . 'client/js/superbundle.js'?>"></script>
    <?php echo $block->getConfigValue('ec/general/code_head')?>
    <!-- End Google Tag Manager -->
    <style>
        body{
            margin: 0px;
        }
        #cookiescript_injected #cookiescript_wrapper #cookiescript_header {
            font-size: 20px;
        }

        #cookiescript_injected #cookiescript_wrapper #cookiescript_description span {
            font-size: 14px;
            line-height: 1;
            font-family: 'Open Sans', Arial, 'Trebuchet MS', 'Segoe UI', 'Helvetica', sans-serif;
        }

        #cookiescript_injected #cookiescript_wrapper #cookiescript_description a#cookiescript_readmore {
            font-size: 14px;
            line-height: 1;
            font-family: 'Open Sans', Arial, 'Trebuchet MS', 'Segoe UI', 'Helvetica', sans-serif;
        }

        #customizer-container .finaloverlay {
            background-color: rgba(17, 17, 17, 0.6);
        }

        .theme-gc #customizer-container .cross-sell .crossmain .crossitem .checkcontainer:hover input~.checkmark,
        .theme-mpx #customizer-container .cross-sell .crossmain .crossitem .checkcontainer:hover input~.checkmark {
            background-color: unset;
        }

        .theme-gc #customizer-container .owl-next span, .theme-gc #customizer-container .owl-prev span,
        .theme-mpx #customizer-container .owl-next span, .theme-mpx #customizer-container .owl-prev span {
            color: #333;
        }

        #customizer-container .cross-sell {
            width: 720px;
            min-width: 720px;
            height: 528px;
            max-height: 528px;
        }

        #customizer-container .cross-sell .crossheader {
            height: 84px;
        }

        #customizer-container .cross-sell .crossmain {
            border: unset;
            height: 360px;
            max-height: 360px;
        }

        #customizer-container .cross-sell .crossmain .owl-stage-outer {
            padding: 10px 0;
        }

        #customizer-container .cross-sell .crossmain .owl-stage-outer .owl-item {
            border-bottom: unset;
            width: calc(720px/3) !important;
        }

        #customizer-container .cross-sell .crossmain .crossitem {
            border-right: solid 1px #CCCCCC;
        }

        #customizer-container .cross-sell .crossmain .crossitem .checkmark {
            width: 24px;
            height: 24px;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossimgholder {
            max-height: 80%;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossimgholder img {
            width: 160px;
            max-height: 80%;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder h2 {
            text-align: left;
            font-weight: 700;
            font-size: 16px;
            margin: 20px;
            margin-bottom: 5px;
            width: auto;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder p.description {
            text-align: left;
            font-weight: 400;
            font-size: 12px;
            margin: 0 20px;
            width: auto;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder .price {
            font-size: 14px;
            font-weight: 800;
            line-height: 1.6;
            text-align: left;
            right: 0;
            left: 24%;
            position: absolute;
            bottom: 10px;
            width: 30%;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder label.checkcontainer {
            font-size: 14px;
            line-height: 1.6;
            text-transform: uppercase;
            right: 0;
            left: 55%;
            position: absolute;
            bottom: 10px;
            padding-left: 10px;
            width: 45%;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder label.checkcontainer .checkmark:after {
            left: 8px;
            top: 2px;
            width: 6px;
            height: 12px;
        }

        #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder label.checkcontainer span.checkmark {
            left: unset;
            margin-left: 6px;
            border-color: #000;
        }

        #customizer-container .cross-sell .crossfooter {
            border: unset;
            border-top: solid 1px #CCCCCC;
            height: 84px
        }

        #customizer-container .cross-sell .crossfooter .crossbuttonholder {
            width: 94%;
            left: 20px;
        }

        #customizer-container .cross-sell .crossfooter .crossbuttonholder p.adjust {
            font-size: 16px;
            font-weight: 700;
        }

        #customizer-container .cross-sell .crossfooter .crossbuttonholder p.concart {
            font-size: 16px;
            font-weight: 500;
            color: #2B2B2B;
        }

        #customizer-container .owl-next,
        #customizer-container .owl-prev {
            -webkit-transform: rotate(45deg);
            transform: rotate(45deg);
            border-style: solid;
            color: transparent;
            border-color: #333333;
            width: 15px;
            height: 15px;
        }

        #customizer-container .owl-next span,
        #customizer-container .owl-prev span {
            color: transparent !important;
            font-size: 12px;
        }

        #customizer-container .owl-prev {
            border-width: 0px 0px 3px 3px;
        }

        #customizer-container .owl-next {
            border-width: 3px 3px 0px 0px;
        }

        /* support for ipad pro 11" */
        @media only screen and (max-width: 1112px)  and (max-height: 834px) {
            #customizer-container .cross-sell .owl-item,
            #customizer-container .cross-sell .owl-stage,
            #customizer-container .cross-sell .owl-wrapper,
            #customizer-container .cross-sell .owl-wrapper-outer {
                height: 97%;
            }
        }

        /* support for ipad pro 13" */
        @media only screen and (max-width: 1366px) and (max-height: 1024px) {
            #customizer-container .cross-sell .owl-item,
            #customizer-container .cross-sell .owl-stage,
            #customizer-container .cross-sell .owl-wrapper,
            #customizer-container .cross-sell .owl-wrapper-outer {
                height: 97%;
            }
        }

        @media only screen and (max-width: 767px) {
            #customizer-container .cross-sell {
                width: 100%;
                min-width: 100%;
                height: 100%;
                max-height: 100%;
            }

            #customizer-container .cross-sell .crossheader h2 {
                font-size: 19px !important;
            }

            #customizer-container .cross-sell .crossmain .crossitem {
                height: auto;
            }

            #customizer-container .cross-sell .crossmain .crossitem .description {
                margin-bottom: 10px;
            }

            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder .price,
            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder .checkcontainer {
                -webkit-transform: none;
                transform: none;
                position: relative;
                bottom: 0;
                left: 0;
                height: 22px;
                margin: 10px 0;
            }

            #customizer-container .cross-sell .crossfooter,
            #customizer-container .cross-sell .crossheader {
                height: 72px;
            }

            #customizer-container .cross-sell .crossfooter {
                border-top: solid 1px #C4C4C4;
            }

            #customizer-container .cross-sell .crossfooter .crossbuttonholder {
                width: 92%;
                left: 15px;
            }

            #customizer-container .cross-sell .crossfooter .crossbuttonholder p.adjust {
                font-size: 14px;
                font-weight: bold;
            }

            #customizer-container .cross-sell .crossfooter .crossbuttonholder p.concart {
                font-size: 14px;
                font-weight: bold;
                color: #2B2B2B;
            }

            #customizer-container .cross-sell .crossheader .kruisje {
                display: none;
            }

            #customizer-container .cross-sell .crossmain {
                height: calc(100% - 144px);
                max-height: calc(100% - 144px);
                border: none;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver {
                transform: none;
                left: unset;
                top: unset;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver {
                overflow-x: hidden;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem {
                border-left: none;
                border-right: none;
                border-bottom: solid 1px #C4C4C4;
                height: auto;
                min-height: 25%;
                background: #ffffff;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem:last-child {
                border-bottom: unset;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossimgholder {
                width: 32%;
                max-width: 32%;
                display: inline-block;
                height: auto;
            }

            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder {
                width: 62%;
                max-width: 62%;
                display: inline-block;
                height: auto;
                margin-left: 10px;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossimgholder img {
                width: auto;
                height: 80%;
                margin-left: 6px;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder h2 {
                font-size: 16px;
                font-weight: bold;
                text-align: left;
                margin-left: 6px;
                margin-top: 10px;
                margin-bottom: 5px;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder p.description {
                text-align: left;
                margin-left: 6px;
                margin-top: 5px;
                margin-bottom: 5px;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder span.price {
                font-size: 16px;
                font-weight: 700;
                line-height: 1.6;
                position: relative;
                width: 30%;
                bottom: 0;
                left: 6px;
                text-align: left;
                float: left;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder label.checkcontainer {
                font-size: 16px;
                font-weight: 700;
                line-height: 1.6;
                position: relative;
                display: inline-block;
                width: 65%;
                bottom: 0;
                left: 0;
                right: 0;
                padding-left: 0;
                padding-right: 10px;
            }
        }

        @media only screen and (max-width: 414px) {
            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder {
                width: 65%;
            }
        }

        @media only screen and (max-width: 414px) and (max-height: 736px) {
            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder {
                max-width: 65%;
            }
        }

        @media only screen and (max-width: 375px) and (max-height: 667px) {
            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder {
                margin-left: 0;
                max-width: 68%;
            }
            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder h2 {
                margin-top: 5px;
                font-size: 14px;
                margin-right: 10px;
            }
            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder p.description {
                margin-right: 10px;
            }
        }

        @media only screen and (max-width: 320px) {
            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder {
                width: 70%;
                max-width: 70%;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder h2 {
                font-size: 13px;
                margin-top: 5px;
                margin-bottom: 5px;
                margin-right: 10px
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder p.description {
                margin-bottom: 5px;
                margin-top: 5px;
                margin-right: 10px;
                font-size: 11px;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder span.price {
                font-size: 12px;
                margin: 6px 0;
                bottom: 0;
                position: relative;
                float: left;
            }

            #customizer-container .cross-sell .crossmain .outerscrollver .innerscrollver .crossitem .crossTextHolder label.checkcontainer {
                font-size: 12px;
                margin: 6px 0;
                bottom: 0;
            }

            #customizer-container .cross-sell .crossfooter .crossbuttonholder p.adjust {
                padding: 12px;
            }

            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder label.checkcontainer span.checkmark {
                width: 18px;
                height: 18px;
            }

            #customizer-container .cross-sell .crossmain .crossitem .crossTextHolder label.checkcontainer .checkmark:after {
                left: 5px;
                top: 1px;
                width: 5px;
                height: 10px;
            }
        }
    </style>
</head>
<body>
<?php echo $block->getConfigValue('ec/general/code_body')?>
<div id="customizer-container" class="full-page">
</div>

<script>
    var setup_options = {
        <?php if($block->getData('customizer_options')):
            foreach($block->getData('customizer_options') as $key => $value):
                echo str_replace('customproduct_','',$key) .':"'.$value.'",';
            endforeach;
        endif;?>
        prod_id : <?php echo $block->getGoCustomizerProductId()?:'0' ?>,
        customer_auth : '<?php echo $block->getCustomerAuth() ?>',
        customizer_session : '<?php echo $block->getCustomizerSession() ?>',
        action : '<?php echo $block->getCustomizerAction() ?>',
        addToCartUrl : '<?php echo $block->getUrl('gocustomizer/customizer/addToCart/');?>',
        backUrl : '<?php echo $block->getRedirectUrl();?>',
        homeUrl : '<?php echo $block->getHomeUrl();?>',
        fbAppId : '<?php echo $block->getConfigValue('designcustomizer/general/facebook_app_id');?>',
        reseller : '<?php echo $block->getConfigValue('gocustomizer/general/reseller_api_key');?>'
    };

    Customizer.init(setup_options);

</script>
</body>
