<?php if ($block->getHelper()->usePostRenderImpressionPayloadModel()):?>

    <script data-ommit="true">

    	require(['jquery'],function($)
    	{
    		var payload = <?php echo $block->getProductList()->getSearchImpressionPayload($block->getLayout()->getBlock('search_result_list')) ?>;
    			
    		payload.ecommerce['impressions'] = (function()
    		{
    			var impressions = [];

    			$('[data-event=productClick]').each(function()
    			{
    				impressions.push(
    				{
    					id: 				   $(this).attr('data-id'),
    					name: 				   $(this).attr('data-name'),
    					category:			   $(this).attr('data-category'),
    					brand:				   $(this).attr('data-brand'),
    					price:		parseFloat($(this).attr('data-price')),
    					position: 	parseFloat($(this).attr('data-position')),
    					list:				   $(this).attr('data-list'),
    					<?php echo $block->getHelper()->getStockDimensionIndex(true) ?>: $(this).attr('data-<?php echo $block->getHelper()->getStockDimensionIndex(true) ?>')
    				});
            	});
    
    			return impressions;
    		})();

    		(function(payload, payload_max_size)
    	    {
    			var payloadSize = AEC.getPayloadSize(payload);
    			
    			if (payload_max_size > payloadSize)
    			{
    				AEC.Cookie.impressions(payload).push(dataLayer, false);

    				<?php
    				/**
    				 * Private browser fallback
    				 */
    				?>
    				
    				dataLayerTransport.push(payload);
    			}
    			else 
    			{
    				var chunks = AEC.getPayloadChunks(payload.ecommerce.impressions, Math.ceil(payload.ecommerce.impressions.length/Math.ceil(payloadSize/payload_max_size)));

    				var lazyPush = function(chunks)
    				{
    					if (chunks.length)
    					{
    						var chunk = chunks.shift(), chunkPush = $.extend({}, payload);

    						chunkPush['event'] 					= 'impression';
    						chunkPush.ecommerce['impressions']  = chunk;
    						chunkPush['eventCallback'] 			= (function(chunks)
    						{
    							return function()
    							{
    								lazyPush(chunks);
    							}
    						})(chunks);

    						(function(data)
    						{
    							AEC.Cookie.impressions(data).push(dataLayer);
    							
    						})(chunkPush);
    					}
    				};

    				/**
    				 * Call lazy push
    				 */
    				lazyPush(chunks);
    			}
    			
        	})(payload, <?php echo \Anowave\Ec\Helper\Constants::GOOGLE_PAYOAD_SIZE ?>);


    		<?php 
    		/**
    		 * AdWords Dynamic Remarketing
    		 */
    		?>
    		window.google_tag_params = window.google_tag_params || {};
    
    		window.google_tag_params.ecomm_pagetype = 'searchresults';
    		window.google_tag_params.ecomm_category = '<?php echo __('Search Results') ?>';
    		window.google_tag_params.returnCustomer = <?php echo $block->getHelper()->getIsReturnCustomer() ?>;
    		
    		<?php
    		/**
    		 * Facebook Pixel Tracking
    		 */
    		?>
    		<?php if ($block->getHelper()->facebook()): ?>

        		if ("undefined" !== typeof fbq)
        		{
            		(function(params)
                    {
            			(function(callback)
    					{
    						if (AEC.Const.COOKIE_DIRECTIVE)
    						{
    							AEC.CookieConsent.queue(callback);
    						}
    						else 
    						{
    							callback.apply(window,[]);
    						}
    					})
    					(
    						(function(params)
    						{
    							return function()
    							{
    								fbq("track", "Search", params);
    							}
    						})(params)
    					);
            			
                    })({ content_ids: payload.ecommerce.impressions.map(function(impression){ return impression.id; }), content_type: 'product_group', content_category: '<?php echo __('Search Results') ?>',search_string: '<?php echo $block->escapeHtml(isset($_GET['q']) ? $_GET['q'] : '') ?>',currency:'<?php echo $block->getHelper()->getCurrency() ?>', value: <?php echo $block->getHelper()->getVisitorId() ?> });
        		}
    		
    		<?php endif ?>
    	});
    </script>
    
<?php endif ?>