<?php
// @codingStandardsIgnoreFile

/**
 * Product view HOW DO I MAKE MY OWN CUSTOM CASE
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php // Get current product
$product = $block->getProduct();
?>
<?php echo $product->getData('how_to_make_case'); ?>
<div>Are you looking for a one-of-a-kind case for your phone? Then you have come to the right place! With GoCustomized
    you can make custom iPhone XS case in only a few clicks. Start by visiting our user-friendly customizer and
    uploading one or more pictures from your phone, computer or social media. Are you undecided about which picture to
    upload? Then take a look at our collection, in which we feature vintage, nature, art designs and more! Next, add
    some text, a sticker and even a filter to your masterpiece. Start right now!
</div>
