<?php if ($block->isLoggedIn()): return; endif; ?>
<div id="contactoverlay">
    <div class="overlayinner">
        <span class="closer"><img src="<?php echo $block->getViewFileUrl('images/close_btn.svg');?>"/> </span>
        <h1 class="section-title"><?= __('Customer Contact'); ?></h1>
        <div class="question-container">
            <div class="question-container-wrapper">
                <p>
                    <?= __('Login to your account'); ?>
                    <span class="tooltip-wrapper">
                        <span class="question-tooltip">?</span>
                        <span class="question-tooltip-message">
                            <?= __( 'Customer accounts are created when you place an order. An email to activate your account was sent the same day. Did not receive that email? Activate your account by resetting your password <a href="%1">here</a>.', $block->escapeUrl($block->getForgotPasswordUrl()) ) ?>
                        </span>
                    </span>
                </p>
            </div>
        </div>
        <form action="" method="post">
            <div class="content">
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><?php echo __('Email Address') ?><em style="color: red">*</em></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="" id="\" class="input-text required-entry validate-email" title="<?php echo __('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><?php echo __('Password') ?><em style="color: red">*</em></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo __('Password') ?>" />
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <a href="<?= $this->getBaseURL() . 'customer/account/forgotpassword/'; ?>"
                   class="f-left firecheckout-forgot">
                    <?php echo __('Forgot Your Password?') ?>
                </a>
                <button type="submit" class="button" title="<?php echo __('Login') ?>" name="send" id="submitlogin"><span><span><?php echo __('Login') ?></span></span></button>
                <span class="please-wait" id="login-please-wait" style="display:none;">
                    <img src="<?php echo $block->getViewFileUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
                </span>
            </div>
            <span class="errormessage"></span>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#submitlogin": {
            "login": {
                "loginUrl": "<?php echo $block->getUrl('helpcenter/contactForm/login') ?>"
            }
        }
    }
</script>
