<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */

$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');

$customizerBlock = $this->getLayout()->createBlock('CustomConcepts\GoCustomizer\Block\Gocustomizer');
$goCustomizerId = $customizerBlock->getGoCustomizerProductId($_product);
$customizerProductType = $customizerBlock->getCustomizerProductType($_product);
?>
<?php if($goCustomizerId != false):?>
        <a class="button btn btn-cart gocustomize" title="<?= __('Design now!') ?>" href="<?= $block->getUrl('gocustomizer/customizer/init/customizable/'.$goCustomizerId.'/type/'.$customizerProductType) ?>"><?= __('Design now!') ?></a>
<?php elseif ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>


<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
