<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>

<div id="sortlistnew" class="mobile-show">
    <div class="scrollouter">
        <div class="scrollinner">
            <ul>
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <?php
                $ascUrlParams = ['product_list_order' => $_key, 'product_list_dir' => 'asc'];
                $descUrlParams = ['product_list_order' => $_key, 'product_list_dir' => 'desc'];
                ?>
                <li>
                    <label title="<?php echo __('Set Ascending Direction') ?>">
                        <input name="sortoption" type="radio" value="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true, '_query' => $ascUrlParams]) ?>" <?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'asc'): ?> checked="checked" <?php endif; ?>/>
                            <?php echo __($_order) ?> - <?php echo __('Set Ascending Direction') ?>
                        <span class="checkmark"></span>
                    </label>
                </li>
                <li>
                    <label title="<?php echo __('Set Descending Direction') ?>">
                        <input name="sortoption" type="radio" value="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true, '_query' => $descUrlParams]) ?>" <?php if($this->isOrderCurrent($_key) && $this->getCurrentDirection() == 'desc'): ?> checked="checked" <?php endif; ?>/>
                            <?php echo __($_order) ?> - <?php echo __('Set Descending Direction') ?>
                        <span class="checkmark"></span>
                    </label>
                </li>
            <?php endforeach; ?>
            </ul>
            <div id="sortbutton_wrap">
                <button id="sortbutton"><?php echo __('sort');?></button>
            </div>
        </div>
    </div>
</div>

<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
        <?php if ($block->isExpanded()): ?>
            <?php echo $this->getLayout()
                ->createBlock('\Magento\Catalog\Block\Product\ProductList\Toolbar')
                ->setTemplate('Magento_Catalog::product/list/toolbar/viewmode.phtml')
                ->toHtml(); ?>
        <?php endif; ?>

        <div class="toolbar-top mobile-hide">
            <div class="toolbar-top-left">
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

                <?php if ($block->isExpanded()): ?>
                    <?php
                    echo $this->getLayout()
                        ->createBlock('\Magento\Catalog\Block\Product\ProductList\Toolbar')
                        ->setTemplate('Magento_Catalog::product/list/toolbar/sorter.phtml')
                        ->toHtml();
                    ?>
                <?php endif; ?>
            </div>

            <?php
            echo $this->getLayout()
                ->createBlock('\Magento\Catalog\Block\Product\ProductList\Toolbar')
                ->setTemplate('Magento_Catalog::product/list/toolbar/limiter.phtml')
                ->toHtml();
            ?>
        </div>
        <?= $block->getPagerHtml() ?>
    </div>
<?php endif ?>


<script type="text/javascript">
    requirejs(['jquery', '!domReady'], function($) {
        $(document).ready(function () {
            $('#sortlistnew.mobile-show input[name="sortoption"][checked] ~ .checkmark').css({'background-color': '#fcc324', 'border': 'none'});

            $('#sortlistnew.mobile-show input[name="sortoption"]').on('change', function(){
                $('#sortlistnew.mobile-show input[name="sortoption"]').parent().find('.checkmark').css({'border': '', 'background-color': ''})
            });
        });
    });
</script>