<?php
$_objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$_config = $_objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');
$_disableDefaultMenu = $_config->getValue('codazon_megamenu/general/disable_default_menu');

$store = $_objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeId = $store->getStore()->getId();

$navClass = [];
if($store->getWebsite()->getCode() == 'custom_concepts'){
    $navClass[] = 'mpc-menu';
}
?>
<?php if($_disableDefaultMenu): ?>
	<?php $_usedMegamenu = $_config->getValue('codazon_megamenu/general/used_megamenu', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $storeId); ?>
	<nav id="mainmenu" class="<?php echo implode(' ', $navClass) ?> cdz-navigation" data-action="navigation">
	<?php echo $_objectManager->get('Codazon\MegaMenu\Block\Widget\Megamenu')->setMenu($_usedMegamenu)->toHtml(); ?>
	</nav>
<?php else: ?>
	<?php echo $_objectManager->get('Magento\Theme\Block\Html\Topmenu')->setTemplate('Magento_Theme::html/topmenu.phtml')->toHtml(); ?>
<?php endif ?>
<p id="translated" style="display: none"><?php echo __('Show more') ?></p>

<?php if($store->getWebsite()->getCode() == 'custom_concepts') { ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "CustomConcepts_MegaMenu/js/custommenu": {}
            }
        }
    </script>
<?php } ?>
