<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
        <div class="pager mobile-hide">
    <?php endif ?>

    <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?= __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?=  __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?= __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
    <?php endif ?>

    <?php if ($block->getLastPageNum()>1): ?>
        <div class="pager-pages mobile-hide">
            <ul class="items pages-items" aria-labelledby="paging-label">
                <?php if (true || !$block->isFirstPage()): ?>
                    <li class="item pages-item-previous">
                        <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                        <a class="<?= $text ? 'link ' : 'action ' ?> previous" href="<?=  $block->getPreviousPageUrl() ?>" title="<?= $text ? $text : __('Previous') ?>">
                            <span>&lt; <?= $text ? $text : __('Previous') ?></span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowFirst()): ?>
                    <li class="item">
                        <a class="page first" href="<?= $block->getFirstPageUrl() ?>">
                            <span>1</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowPreviousJump()): ?>
                    <li class="item">
                        <a class="page previous jump" title="" href="<?= $block->getPreviousJumpUrl() ?>">
                            <span>...</span>
                        </a>
                    </li>
                <?php endif;?>

                <ul class="page-numbers">
                    <?php foreach ($block->getFramePages() as $_page): ?>
                        <?php if ($block->isPageCurrent($_page)): ?>
                            <li class="item current">
                                <strong class="page">
                                    <span><?= $_page ?></span>
                                </strong>
                            </li>
                        <?php else: ?>
                            <li class="item">
                                <a href="<?= $block->getPageUrl($_page) ?>" class="page">
                                    <span><?= $_page ?></span>
                                </a>
                            </li>
                        <?php endif;?>
                    <?php endforeach;?>
                </ul>

                <?php if ($block->canShowNextJump()): ?>
                    <li class="item">
                        <a class="page next jump" title="" href="<?= $block->getNextJumpUrl() ?>">
                            <span>...</span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($block->canShowLast()): ?>
                    <li class="item">
                        <a class="page last" href="<?= $block->getLastPageUrl() ?>">
                            <span><?= $block->getLastPageNum() ?></span>
                        </a>
                    </li>
                <?php endif;?>

                <?php if (!$block->isLastPage()): ?>
                    <li class="item pages-item-next">
                        <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                        <a class="<?= $text ? 'link ' : 'action ' ?> next" href="<?= $block->getNextPageUrl() ?>" title="<?= $text ? $text : __('Next') ?>">
                            <span><?= $text ? $text : __('Next') ?> &gt;</span>
                        </a>
                    </li>
                <?php endif;?>
            </ul>
        </div>
    <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter">
            <strong class="limiter-label"><?=  __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?= $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?= $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?=  __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif ?>
