<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
// $block CustomConcepts\UltimoGocustomized\Block\Helplink
?>
<?php if($block->customerLoggedIn()): ?>
<li><a href="<?php echo $block->getAccountLink(); ?>"><?php echo __('Account'); ?></a></li>
<?php else: ?>
<li class="nav item"><a href="<?php echo $block->getHelpLink(); ?>"><?php echo __('Help'); ?></a></li>
<?php endif; ?>