<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var Magento\Sales\Block\Order\Email\Shipment\Items $block */
/** @var CustomConcepts\GoCustomizer\ViewModel\GocustomizerViewModel $gcViewModel */
$gcViewModel = $block->getGcViewModel();
$gcHelper = $gcViewModel->getGcHelper();
?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order    = $block->getOrder() ?>
<?php if ($_shipment && $_order) : ?>
    <table class="shipment-items-gc">
        <?php foreach ($_shipment->getAllItems() as $_item) : ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <?php $product = $gcViewModel->getProductById($_item->getProductId()); ?>
                <tbody>
                    <tr>
                        <td style="text-align: center">
                            <?php if ($gcHelper->isGocustomizerProduct($_item)): ?>
                                <img alt="<?= $product->getName(); ?>" src="<?= $gcHelper->getProductThumbnail($_item->getOrderItem()); ?>" height="160"/>
                            <?php else: ?>
                                <img alt="<?= $product->getName(); ?>" src="<?= $gcHelper->getProductDefaultThumbnail($_item->getOrderItem()); ?>" height="160"/>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="text-align: center"><p><b><?= $product->getName(); ?></b></p></td>
                    </tr>
                    <tr>
                        <td style="text-align: center">
                            <span style="border-right: 1px solid black; padding-right: 10px;"><?= $product->getAttributeText('customproduct_color'); ?></span>
                            <span style="padding-left: 10px;"><?= number_format($_item->getQty()); ?>&nbsp;<?= ($_item->getQty() > 1) ? __('Items') : __('Item'); ?></span>
                        </td>
                    </tr>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
