<?php
    /** @var Magento\Framework\View\Element\Template $block */
?>
<div class="form-content order-search-wrapper">
    <form action="<?= $block->getUrl('*/*/*'); ?>" id="my_order_search" method="get">
        <input type="text" id="order_search" name="order_search" class="input-text order-search-input">
        <input class="button small-links order-search-button" type="submit" value="Search">
    </form>
</div>
